numSupervisors: 2

image:
  repository: nexus.redplanetlabs.com:8000/repository/docker/rama-amd64
  pullPolicy: IfNotPresent
  tag: 0.16.0

zookeeper:
  servers:
    - "my-zookeeper-0.my-zookeeper-headless.zookeeper.svc.cluster.local"

conductor:
  cpu: 1
  memory: "5Gi"
  storageClassName: "local-storage-conductor"
  storageAmount: "10Gi"

supervisor:
  cpu: 1.5
  memory: "6Gi"
  storageClassName: "local-storage-supervisor"
  storageAmount: "10Gi"
