apiVersion: v1
kind: Service
metadata:
  name: conductor
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: rama
    role: conductor
  ports:
    - name: http
      port: 8888
      targetPort: 8888
    - name: rpc
      port: 1973
      targetPort: 1973
