apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: conductor
spec:
  selector:
    matchLabels:
      app: rama
      role: conductor
  serviceName: "conductor"
  replicas: 1
  volumeClaimTemplates:
  - metadata:
      name: rama-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: {{ .Values.conductor.storageClassName}}
      resources:
        requests:
          storage: {{ .Values.conductor.storageAmount}}
  template:
    metadata:
      labels:
        app: rama
        role: conductor
    spec:
      nodeSelector:
{{ .Values.nodeSelector | toYaml | indent 6 }}
      imagePullSecrets:
        - name: rpl-docker-secret
      initContainers:
        {{ include "shared.initContainer.copyRelease" . | nindent 8 }}
        - name: overwrite-config
          image: busybox
          command: ["/bin/sh"]
          args:
          - "-c"
          - >-
            cp /config/rama.yaml /data/rama/
          volumeMounts:
          - name: rama-data
            mountPath: /data/rama
          - name: config-volume
            mountPath: /config
      containers:
        - name: conductor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          resources:
            requests:
              memory: "{{ .Values.conductor.memory }}"
              cpu: "{{ .Values.conductor.cpu }}"
            limits:
              memory: "{{ .Values.conductor.memory }}"
              cpu: "{{ .Values.conductor.cpu }}"
          workingDir: /data/rama
          command: ["./rama", "conductor"]
          ports:
            - containerPort: 8888
            - containerPort: 1973
          volumeMounts:
            - name: rama-data
              mountPath: /data/rama
      volumes:
        - name: config-volume
          configMap:
            name: rama-config
